### ISSUE TITLE
[W7-Kaggle-Competition] María PdAS

### ISSUE THREAD

**Issue by mariaperezdeayalas** [Ironhack-Data-Madrid-Octubre-2021/W7-Kaggle_competition#12]
https://github.com/mariaperezdeayalas/Diamonds-Kaggle-Competition-

**Comment by yamadajc** [comment]
Hola hola Maria!

A por el ultimo proyecto!!🚀🚀🚀

# Kaggle_competition 

En general, los objetivos y estrategias del proyecto:

Hay que elegir el modelo que mejor te prediga en base a unos datos. Para elegir el mejor modelo de machine learning, hay cuatro variables que podemos controlar:

- Procesamiento de los datos
- Como separamos los datos para hacer el train/test.
- Qué modelo utilizamos.
- Qué parámetros utilizamos en ese modelo.


Para cada uno de ellos hay una estrategia:

- Encoders & Standarization: para las variables categóricas: [aquí](https://medium.com/@michaeldelsole/what-is-one-hot-encoding-and-how-to-do-it-f0ae272f1179) (también hay otras estrategias, como [ésta](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html), o incluso hacer un diccionario donde a cada letra le asignes un valor numérico relativo al resto. Claro que esto te puede valer cuando tienes pocos datos.
- Cross-validation: para garantizar el corte de los datos: [aquí](https://medium.com/analytics-vidhya/deeply-explained-cross-validation-in-ml-ai-2e846a83f6ed)
- Modelo de regresión: probar varios, [aquí](https://medium.com/technology-nineleaps/popular-machine-learning-algorithms-a574e3835ebb)
- Grid search: para las permutaciones de los parámetros: [aquí](https://medium.com/fintechexplained/what-is-grid-search-c01fe886ef0a)




# FeedBack 
Has creado un repositorio con un buen readme. Me describes el workflow y la estructura del repositorio. 

Por cierto se te a pasado un `.DS_Store` fuera del `.gitignore`. Recuerda que es lo primero que debemos crear. De lo contrario se quedara en cache y por mucho que lo metas después del primer push quedará registrado. 

Has procesado los datos, entrenado un modelo, has hecho GridSearchCV y has hecho submissions. Tan solo nos faltarían  un par de slide para explicar el proceso. Recuerda que era necesario para este proyecto. 


Por último, explora [H20](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html) , tendrás que instalar Java. Pero te aseguro que es magia en estado puro. 

Buen trabajo y a por el proyecto!!!
