### ISSUE TITLE
[W7-Kaggle_competition]BeaSánchez

### ISSUE THREAD

**Issue by Beapsp** [Ironhack-Data-Madrid-Octubre-2021/W7-Kaggle_competition#14]
https://github.com/Beapsp/Proyecto5_Machine_Learning

**Comment by yamadajc** [comment]
Hola hola Bea!

A por el ultimo proyecto!!🚀🚀🚀

# Kaggle_competition 

En general, los objetivos y estrategias del proyecto:

Hay que elegir el modelo que mejor te prediga en base a unos datos. Para elegir el mejor modelo de machine learning, hay cuatro variables que podemos controlar:

- Procesamiento de los datos
- Como separamos los datos para hacer el train/test.
- Qué modelo utilizamos.
- Qué parámetros utilizamos en ese modelo.


Para cada uno de ellos hay una estrategia:

- Encoders & Standarization: para las variables categóricas: [aquí](https://medium.com/@michaeldelsole/what-is-one-hot-encoding-and-how-to-do-it-f0ae272f1179) (también hay otras estrategias, como [ésta](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html), o incluso hacer un diccionario donde a cada letra le asignes un valor numérico relativo al resto. Claro que esto te puede valer cuando tienes pocos datos.
- Cross-validation: para garantizar el corte de los datos: [aquí](https://medium.com/analytics-vidhya/deeply-explained-cross-validation-in-ml-ai-2e846a83f6ed)
- Modelo de regresión: probar varios, [aquí](https://medium.com/technology-nineleaps/popular-machine-learning-algorithms-a574e3835ebb)
- Grid search: para las permutaciones de los parámetros: [aquí](https://medium.com/fintechexplained/what-is-grid-search-c01fe886ef0a)




# FeedBack 
Que alegria me das. Bien Bea!
Has creado un repositorio con un muy buen readme. Por cierto se te a pasado un `.ipynb_checkpoints` fuera del `.gitignore`.

Has procesado los datos, entrenado un modelo, has hecho GridSearchCV, has hecho submissions y ademas un par de slide para explicar el proceso.  De verdad que todo bien  


Por último, explora [H20](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html) , tendrás que instalar Java. Pero te aseguro que es magia en estado puro. 

Muchas gracias y animo con el proyecto!
