### ISSUE TITLE
[W7-Kaggle_competition]Daniela Arias

### ISSUE THREAD

**Issue by daniela-arias** [Ironhack-Data-Madrid-Octubre-2021/W7-Kaggle_competition#2]
https://github.com/daniela-arias/Diamonds_competition

**Comment by yamadajc** [comment]
Hola hola Daniela,
Sabemos que has trabajado, pero sintiendo lo  mucho, un proyecto sin readme es un proyecto NO entregado.  Aun asi, hemos optado por no considerarte el proyecto como no enviado, pero no se te mandará feedback sobre tu trabajo.
Ahora enfoca te en el proyecto y no pienses en nada mas 💪
