### ISSUE TITLE
silvia Rico Diamantes

### ISSUE THREAD

**Issue by silviarico** [Ironhack-Data-Madrid-Octubre-2021/W7-Kaggle_competition#21]
https://github.com/silviarico/W7-diamonds_kaggle.git

**Comment by yamadajc** [comment]
Hola Silvia,
Lo sentimos mucho, pero sabras un proyecto sin readme es un proyecto NO entregado. Aun asi, hemos optado por no considerarte el proyecto como no enviado, pero no se te mandará feedback sobre tu trabajo.
Saludos y a por el proyecto 💪
