### ISSUE TITLE
[Kaggle Diamonds] Andrés Uzcátegui

### ISSUE THREAD

**Issue by baccandres** [Ironhack-Data-Madrid-Octubre-2021/W7-Kaggle_competition#3]

**Comment by baccandres** [comment]
https://github.com/baccandres/DiamondPricingModel

**Comment by yamadajc** [comment]
Buenas Andres ,
Lo sentimos mucho, pero sabras que un proyecto sin readme es un proyecto NO entregado. Tan solo nos dejas enlaces. Aun asi, hemos optado por no considerarte el proyecto como no enviado, pero no se te mandará feedback sobre tu trabajo.
Animo y a por el proyecto 💪

**Comment by baccandres** [comment]
Sorry, lo sé, pero estoy destruido!!! Gracias ;)
