### ISSUE TITLE
[Kaggle-Competition] Roberto Alonso

### ISSUE THREAD

**Issue by Roblak96** [Ironhack-Data-Madrid-Octubre-2021/W7-Kaggle_competition#8]

**Comment by Roblak96** [comment]
https://github.com/Roblak96/Kaggle-Competition

**Comment by yamadajc** [comment]
Hola hola Roberto,
Lo sentimos mucho, pero sabras un proyecto sin readme es un proyecto NO entregado. Pero nos dejas el enlace a git de Maria… no entendemos que nos quieres decir. Aun asi, hemos optado por no considerarte el proyecto como no enviado, pero no se te mandará feedback sobre tu trabajo.
Saludos y a por el proyecto 💪

**Comment by Roblak96** [comment]
Joder soy gilipollas, me puse el enlace de María por que lo hablé con ella
para fijarme y hacer mejor el Readme, no copiarlo, si no fijarme en la
estructura y tal,
y como estuve con problemas con el ordena que se lo comenté a Ras, lo hice
al final mal deprisa y corriendo, y se me piró totalmente, no sé por qué
pensaba que ya lo había cmabiado, pero bueno, gracias de todas formas!!
Creo y espero que sea el único con éste error.
